import oracledb
import getpass

# ============================================================
# RAININTEL - APPLICATION DATABASE SETUP
# ============================================================

print("=" * 70)
print("RAININTEL APPLICATION DATABASE SETUP")
print("=" * 70)

password = getpass.getpass("Enter RAININTEL password: ")

connection = oracledb.connect(
    user="RAININTEL",
    password=password,
    dsn="localhost:1521/XEPDB1"
)


cursor = connection.cursor()

print("\nConnected to Oracle successfully.")


# ============================================================
# HELPER
# ============================================================

def table_exists(table_name):
    cursor.execute("""
        SELECT COUNT(*)
        FROM USER_TABLES
        WHERE TABLE_NAME = :1
    """, [table_name.upper()])

    return cursor.fetchone()[0] > 0


def create_table(name, sql):
    if table_exists(name):
        print(f"[SKIP] {name} already exists.")
        return

    cursor.execute(sql)
    print(f"[CREATED] {name}")


# ============================================================
# 1. ROLES
# ============================================================

create_table("ROLES", """
CREATE TABLE ROLES (
    ROLE_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ROLE_NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(255),

    CONSTRAINT PK_ROLES
        PRIMARY KEY (ROLE_ID),

    CONSTRAINT UK_ROLES_NAME
        UNIQUE (ROLE_NAME)
)
""")


# ============================================================
# 2. USERS
# ============================================================

create_table("USERS", """
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    USERNAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,

    FULL_NAME VARCHAR2(150) NOT NULL,

    ROLE_ID NUMBER NOT NULL,
    DISTRICT_ID NUMBER,

    STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,

    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_USERS
        PRIMARY KEY (USER_ID),

    CONSTRAINT UK_USERS_USERNAME
        UNIQUE (USERNAME),

    CONSTRAINT UK_USERS_EMAIL
        UNIQUE (EMAIL),

    CONSTRAINT FK_USERS_ROLE
        FOREIGN KEY (ROLE_ID)
        REFERENCES ROLES(ROLE_ID),

    CONSTRAINT FK_USERS_DISTRICT
        FOREIGN KEY (DISTRICT_ID)
        REFERENCES RAINFALL_DISTRICTS(DISTRICT_ID),

    CONSTRAINT CK_USERS_STATUS
        CHECK (STATUS IN ('ACTIVE', 'INACTIVE'))
)
""")


# ============================================================
# 3. FIELD ASSESSMENTS
# ============================================================

create_table("FIELD_ASSESSMENTS", """
CREATE TABLE FIELD_ASSESSMENTS (
    ASSESSMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    ENGINEER_ID NUMBER NOT NULL,
    DISTRICT_ID NUMBER NOT NULL,

    LATITUDE NUMBER(10,7) NOT NULL,
    LONGITUDE NUMBER(10,7) NOT NULL,

    ADDRESS VARCHAR2(500),

    BUILDING_TYPE VARCHAR2(100),

    ROOF_AREA_M2 NUMBER(12,2),
    ROOF_MATERIAL VARCHAR2(100),
    ROOF_SLOPE NUMBER(8,2),

    WATER_DEMAND_LPD NUMBER(12,2),

    PURPOSE VARCHAR2(200),

    STATUS VARCHAR2(30) DEFAULT 'DRAFT' NOT NULL,

    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_FIELD_ASSESSMENTS
        PRIMARY KEY (ASSESSMENT_ID),

    CONSTRAINT FK_ASSESSMENTS_ENGINEER
        FOREIGN KEY (ENGINEER_ID)
        REFERENCES USERS(USER_ID),

    CONSTRAINT FK_ASSESSMENTS_DISTRICT
        FOREIGN KEY (DISTRICT_ID)
        REFERENCES RAINFALL_DISTRICTS(DISTRICT_ID),

    CONSTRAINT CK_ASSESSMENTS_LATITUDE
        CHECK (LATITUDE BETWEEN -90 AND 90),

    CONSTRAINT CK_ASSESSMENTS_LONGITUDE
        CHECK (LONGITUDE BETWEEN -180 AND 180),

    CONSTRAINT CK_ASSESSMENTS_ROOF_AREA
        CHECK (
            ROOF_AREA_M2 IS NULL
            OR ROOF_AREA_M2 >= 0
        ),

    CONSTRAINT CK_ASSESSMENTS_STATUS
        CHECK (
            STATUS IN (
                'DRAFT',
                'SUBMITTED',
                'APPROVED',
                'REJECTED'
            )
        )
)
""")


# ============================================================
# 4. ASSESSMENT RAINFALL
# ============================================================

create_table("ASSESSMENT_RAINFALL", """
CREATE TABLE ASSESSMENT_RAINFALL (
    ASSESSMENT_RAINFALL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    ASSESSMENT_ID NUMBER NOT NULL,

    RAINFALL_RECORD_ID NUMBER,

    OBSERVATION_DATE DATE,

    ACTUAL_MM NUMBER,
    NORMAL_MM NUMBER,
    DEPARTURE_PERCENT NUMBER,
    CATEGORY VARCHAR2(50),

    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ASSESSMENT_RAINFALL
        PRIMARY KEY (ASSESSMENT_RAINFALL_ID),

    CONSTRAINT UK_ASSESSMENT_RAINFALL
        UNIQUE (ASSESSMENT_ID),

    CONSTRAINT FK_ASSESSMENT_RAINFALL
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES FIELD_ASSESSMENTS(ASSESSMENT_ID),

    CONSTRAINT FK_ASSESSMENT_RAIN_RECORD
        FOREIGN KEY (RAINFALL_RECORD_ID)
        REFERENCES RAINFALL_RECORDS(RAINFALL_ID)
)
""")


# ============================================================
# 5. ASSESSMENT SOIL
# ============================================================

create_table("ASSESSMENT_SOIL", """
CREATE TABLE ASSESSMENT_SOIL (
    ASSESSMENT_SOIL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    ASSESSMENT_ID NUMBER NOT NULL,

    GRID_CELL_ID NUMBER,

    SANDY_FRACTION NUMBER,
    LOAMY_FRACTION NUMBER,
    CLAYEY_FRACTION NUMBER,
    CLAYEY_SKELETAL_FRACTION NUMBER,

    DEPTH_0_25_FRACTION NUMBER,
    DEPTH_25_50_FRACTION NUMBER,
    DEPTH_50_75_FRACTION NUMBER,
    DEPTH_75_100_FRACTION NUMBER,
    DEPTH_100_150_FRACTION NUMBER,
    DEPTH_150_200_FRACTION NUMBER,

    ORGANIC_CARBON_KG_M2 NUMBER,
    INORGANIC_CARBON_KG_M2 NUMBER,

    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_ASSESSMENT_SOIL
        PRIMARY KEY (ASSESSMENT_SOIL_ID),

    CONSTRAINT UK_ASSESSMENT_SOIL
        UNIQUE (ASSESSMENT_ID),

    CONSTRAINT FK_ASSESSMENT_SOIL
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES FIELD_ASSESSMENTS(ASSESSMENT_ID),

    CONSTRAINT FK_ASSESSMENT_SOIL_GRID
        FOREIGN KEY (GRID_CELL_ID)
        REFERENCES SOIL_GRID_CELLS(GRID_CELL_ID)
)
""")


# ============================================================
# 6. RWH RESULTS
# ============================================================

create_table("RWH_RESULTS", """
CREATE TABLE RWH_RESULTS (
    RESULT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    ASSESSMENT_ID NUMBER NOT NULL,

    ANNUAL_RAINFALL_MM NUMBER,
    RUNOFF_COEFFICIENT NUMBER,

    HARVESTABLE_WATER_L NUMBER,
    RECHARGE_POTENTIAL_L NUMBER,

    RECOMMENDED_STORAGE_L NUMBER,

    CALCULATION_METHOD VARCHAR2(100),

    CALCULATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_RWH_RESULTS
        PRIMARY KEY (RESULT_ID),

    CONSTRAINT UK_RWH_RESULTS_ASSESSMENT
        UNIQUE (ASSESSMENT_ID),

    CONSTRAINT FK_RWH_RESULTS_ASSESSMENT
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES FIELD_ASSESSMENTS(ASSESSMENT_ID),

    CONSTRAINT CK_RUNOFF_COEFFICIENT
        CHECK (
            RUNOFF_COEFFICIENT IS NULL
            OR RUNOFF_COEFFICIENT BETWEEN 0 AND 1
        ),

    CONSTRAINT CK_HARVESTABLE_WATER
        CHECK (
            HARVESTABLE_WATER_L IS NULL
            OR HARVESTABLE_WATER_L >= 0
        ),

    CONSTRAINT CK_RECHARGE_POTENTIAL
        CHECK (
            RECHARGE_POTENTIAL_L IS NULL
            OR RECHARGE_POTENTIAL_L >= 0
        )
)
""")


# ============================================================
# 7. RWH RECOMMENDATIONS
# ============================================================

create_table("RWH_RECOMMENDATIONS", """
CREATE TABLE RWH_RECOMMENDATIONS (
    RECOMMENDATION_ID NUMBER GENERATED BY DEFAULT AS IDENTITY,

    ASSESSMENT_ID NUMBER NOT NULL,

    SYSTEM_TYPE VARCHAR2(150),
    STORAGE_CAPACITY_L NUMBER,

    RECHARGE_TYPE VARCHAR2(150),
    FILTER_TYPE VARCHAR2(150),

    CONFIDENCE_SCORE NUMBER(5,2),

    RECOMMENDATION_REASON VARCHAR2(1000),

    CREATED_AT TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT PK_RWH_RECOMMENDATIONS
        PRIMARY KEY (RECOMMENDATION_ID),

    CONSTRAINT FK_RWH_RECOMMENDATIONS
        FOREIGN KEY (ASSESSMENT_ID)
        REFERENCES FIELD_ASSESSMENTS(ASSESSMENT_ID),

    CONSTRAINT CK_RECOMMENDATION_CONFIDENCE
        CHECK (
            CONFIDENCE_SCORE IS NULL
            OR CONFIDENCE_SCORE BETWEEN 0 AND 100
        ),

    CONSTRAINT CK_RECOMMENDATION_STORAGE
        CHECK (
            STORAGE_CAPACITY_L IS NULL
            OR STORAGE_CAPACITY_L >= 0
        )
)
""")


# ============================================================
# INDEXES
# ============================================================

indexes = [
    (
        "IDX_USERS_ROLE",
        "CREATE INDEX IDX_USERS_ROLE ON USERS(ROLE_ID)"
    ),
    (
        "IDX_USERS_DISTRICT",
        "CREATE INDEX IDX_USERS_DISTRICT ON USERS(DISTRICT_ID)"
    ),
    (
        "IDX_ASSESSMENTS_ENGINEER",
        "CREATE INDEX IDX_ASSESSMENTS_ENGINEER ON FIELD_ASSESSMENTS(ENGINEER_ID)"
    ),
    (
        "IDX_ASSESSMENTS_DISTRICT",
        "CREATE INDEX IDX_ASSESSMENTS_DISTRICT ON FIELD_ASSESSMENTS(DISTRICT_ID)"
    ),
    (
        "IDX_ASSESSMENTS_LOCATION",
        "CREATE INDEX IDX_ASSESSMENTS_LOCATION ON FIELD_ASSESSMENTS(LATITUDE, LONGITUDE)"
    ),
    (
        "IDX_ASSESSMENTS_STATUS",
        "CREATE INDEX IDX_ASSESSMENTS_STATUS ON FIELD_ASSESSMENTS(STATUS)"
    ),
    (
        "IDX_RWH_RECOMMENDATIONS_ASSESSMENT",
        "CREATE INDEX IDX_RWH_RECOMMENDATIONS_ASSESSMENT ON RWH_RECOMMENDATIONS(ASSESSMENT_ID)"
    )
]

print("\nCreating indexes...")

for index_name, sql in indexes:
    cursor.execute("""
        SELECT COUNT(*)
        FROM USER_INDEXES
        WHERE INDEX_NAME = :1
    """, [index_name])

    if cursor.fetchone()[0] == 0:
        cursor.execute(sql)
        print(f"[CREATED] {index_name}")
    else:
        print(f"[SKIP] {index_name} already exists.")


# ============================================================
# INSERT DEFAULT ROLES
# ============================================================

print("\nCreating default roles...")

roles = [
    (
        "SUPER_ADMIN",
        "System administrator with complete access"
    ),
    (
        "DISTRICT_ADMIN",
        "Administrator responsible for district operations"
    ),
    (
        "FIELD_ENGINEER",
        "Field engineer who performs building assessments"
    )
]

for role_name, description in roles:

    cursor.execute("""
        SELECT COUNT(*)
        FROM ROLES
        WHERE ROLE_NAME = :1
    """, [role_name])

    if cursor.fetchone()[0] == 0:

        cursor.execute("""
            INSERT INTO ROLES (
                ROLE_NAME,
                DESCRIPTION
            )
            VALUES (
                :1,
                :2
            )
        """, [role_name, description])

        print(f"[CREATED ROLE] {role_name}")

    else:
        print(f"[SKIP ROLE] {role_name} already exists.")


# ============================================================
# COMMIT
# ============================================================

connection.commit()

print("\n" + "=" * 70)
print("APPLICATION DATABASE SETUP COMPLETE")
print("=" * 70)


# ============================================================
# VERIFY TABLES
# ============================================================

print("\nApplication tables:")

cursor.execute("""
    SELECT TABLE_NAME
    FROM USER_TABLES
    WHERE TABLE_NAME IN (
        'ROLES',
        'USERS',
        'FIELD_ASSESSMENTS',
        'ASSESSMENT_RAINFALL',
        'ASSESSMENT_SOIL',
        'RWH_RESULTS',
        'RWH_RECOMMENDATIONS'
    )
    ORDER BY TABLE_NAME
""")

for row in cursor:
    print("  ", row[0])


# ============================================================
# VERIFY ROLES
# ============================================================

print("\nRoles:")

cursor.execute("""
    SELECT ROLE_ID, ROLE_NAME
    FROM ROLES
    ORDER BY ROLE_ID
""")

for row in cursor:
    print("  ", row)


# ============================================================
# CLOSE
# ============================================================

cursor.close()
connection.close()

print("\nOracle connection closed.")
print("=" * 70)