server:
  port: ${PORT:8888}

spring:
  application:
    name: config-server

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:native}

  cloud:
    config:
      server:
        native:
          search-locations: file:../config-repo

        git:
          uri: ${GIT_URI:https://github.com/shanmu2710/RainIntel.git}
          default-label: ${GIT_LABEL:feature/person1-backend-integration-clean}
          search-paths:
            - backend/config-repo
          username: ${GIT_USERNAME:}
          password: ${GIT_TOKEN:}